AWSTemplateFormatVersion: '2010-09-09'
Description: Static Website Creation for ${FQDN}
Resources:
  DNSZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: '${FQDN}'
      Name: '${FQDN}'

  Certificate: 
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: ${FQDN}
      DomainValidationOptions:
        - DomainName:   ${FQDN}
          HostedZoneId: !Ref: 'DNSZone'
      ValidationMethod: DNS

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${BUCKETNAME}
      LifecycleConfiguration:
        Rules:
          - Id: Standard-IA-Storage
            Status: Enabled
            Transitions:
              - TransitionInDays: 60
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
            Id: CORSRuleId1
      Tags:
        - Key: Name
          Value: ${BUCKETNAME}
        - Key: role
          Value: storage
    DependsOn: CloudFrontOriginAccessIdentity

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3Bucket'
      PolicyDocument:
        Id: OriginAccessBucketPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowOringAccessRead
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              - 'arn:aws:s3:::${BUCKETNAME}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
    DependsOn: S3Bucket
  
  LambdaEdgeFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          'use strict';
          exports.handler = (event, context, callback) => {
              
              //Get contents of response
              const response = event.Records[0].cf.response;
              const headers = response.headers;

          //Set new headers 
          headers['strict-transport-security'] = [{key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubdomains; preload'}]; 
          //headers['content-security-policy'] = [{key: 'Content-Security-Policy', value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"}]; 
          headers['x-content-type-options'] = [{key: 'X-Content-Type-Options', value: 'nosniff'}]; 
          headers['x-frame-options'] = [{key: 'X-Frame-Options', value: 'DENY'}]; 
          headers['x-xss-protection'] = [{key: 'X-XSS-Protection', value: '1; mode=block'}]; 
          headers['referrer-policy'] = [{key: 'Referrer-Policy', value: 'same-origin'}]; 
              
              //Return modified response
              callback(null, response);
          };
      Description: ${PROJECT}
      FunctionName: '${PROJECT}-sec-hdrs'
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      Runtime: 'nodejs12.x'
      Timeout: 25
      Tags:
        - Key: Name
          Value: ${PROJECT}-Lambda-Function
        - Key: role
          Value: lamdba-function

  Lambdaversion:
    Type: AWS::Lambda::Version
    Properties: 
      FunctionName: !Ref LambdaEdgeFunction
      Description: v1

  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: 'AllowLambdaServiceToAssumeRole'
            Effect: 'Allow'
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
              - 'lambda.amazonaws.com'
              - 'edgelambda.amazonaws.com'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${FQDN}
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          MaxTTL: 31536000
          TargetOriginId: ${FQDN}-${BUCKETNAME}
          LambdaFunctionAssociations:
            - 
              EventType: origin-response
              LambdaFunctionARN: !Ref Lambdaversion
          ViewerProtocolPolicy: 'redirect-to-https'
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/index.html'
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: '/index.html'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        Logging:
          Bucket: ${BUCKETNAME}.s3.us-east-1.amazonaws.com
          IncludeCookies: false
          Prefix: 'cdn/'
        Origins:
          - DomainName: ${BUCKETNAME}.s3.us-east-1.amazonaws.com
            Id: ${FQDN}-${BUCKETNAME}
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'Certificate'
          MinimumProtocolVersion: 'TLSv1.1_2016'
          SslSupportMethod: 'sni-only'
      Tags:
        - Key: Name
          Value: ${PROJECT}
        - Key: role
          Value: cloudfront-distribution

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront OAI for ${FQDN}'
        
  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref: 'DNSZone'
      # Use this Recordset block if the site will NOT be behind Okta
      RecordSets:
      - Name: ${FQDN}
        Type: 'A'
        AliasTarget:
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
          EvaluateTargetHealth: false
          # The  following HosteZoneId is always used for alias records pointing to CF.
          HostedZoneId: Z2FDTNDATAQYW2