name: GrubTrucks Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

env:
    FQDN: grubtrucks.patrickbosley.com
    BUCKETNAME: grubtrucks.patrickbosley.com
    STACK_NAME: grubtrucks-patrickbosley-com
    ENV: dev
    ORGUNIT: it
    PROJECT: grubtrucks.patrickbosley.com
    REQUESTER: pbosley

jobs:
  test:
    runs-on: ubuntu-20.04
    name: AWS CLI Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: DeploymentSession
        
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 2
        
    - name: Print AWS CLI Version
      run: aws --version
      
    - name: Environment Substitution
      run: envsubst '${ENV} ${STACK_NAME} ${REQUESTER} ${PROJECT} ${ORGUNIT} ${FQDN} ${DNSZONEID} ${BUCKETNAME}' < ./aws/static-web.yml > deploy.yml
      
    - name: Deploy CLoudFormation Template
      run: |
        echo Deploying ${STACK_NAME}
        chmod +x ./cfn_wrapper.sh
        source ./cfn_wrapper.sh
        cfn_wrapper aws cloudformation deploy --template-file deploy.yml --stack-name ${STACK_NAME} --force-upload --capabilities CAPABILITY_NAMED_IAM --tags Name=${STACK_NAME} Stackname=${STACK_NAME} env=${ENV} orgunit=${ORGUNIT} project=${PROJECT} role=cloudformation-stack requester=${REQUESTER} reponame=${GITHUB_REPOSITORY}
      shell: bash

    - name: Copy Source Files to S3 Bucket
      run: aws s3 cp --recursive src/  s3://${BUCKETNAME}
