name: test-action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: AWS CLI Test
    steps:
      - name: Test ${{ matrix.TEST_NAME }}
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - run: aws --version
      - run: aws ec2 describe-instances
        shell: bash
