name: GrubTrucks Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

env:
    FQDN: grubtrucks.patrickbosley.com
    DEPLOYBUCKET: grubtruck-deploy
    BUCKETNAME: grubtrucks.patrickbosley.com
    WEBSTACK: grubtrucks-patrickbosley-com
    DNSSTACK: grubtrucks-patrickbosley-com-dns
    ENV: dev
    ORGUNIT: it
    PROJECT: grubtrucks-patrickbosley-com
    REQUESTER: pbosley

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy GrubTrucks to AWS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: DeploymentSession
        
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 2
      
    - name: Deploy DNS Prep CloudFormation Template
      if: | 
        contains(github.event.head_commit.message, 'dnsprep') &&
        contains(github.event.head_commit.message, 'infra')
      run: |
        echo Performing Variable Substitution
        envsubst '${ENV} ${DNSSTACK} ${REQUESTER} ${PROJECT} ${ORGUNIT} ${FQDN} ${DEPLOYBUCKET}' < ./aws/dnsprep.yml > dnsdeploy.yml
        echo Deploying ${DNSSTACK}
        chmod +x ./cfn_wrapper.sh
        source ./cfn_wrapper.sh
        cfn_wrapper aws cloudformation deploy --template-file dnsdeploy.yml --stack-name ${DNSSTACK} --force-upload --tags Name=${DNSSTACK} Stackname=${DNSSTACK} env=${ENV} orgunit=${ORGUNIT} project=${PROJECT} role=cloudformation-stack requester=${REQUESTER} reponame=${GITHUB_REPOSITORY}
      shell: bash

    - name: Zip and Copy Lambda Function to Deploy Bucket
      if: "!contains(github.event.head_commit.message, 'dnsprep')"
      run: |
        echo Zipping Security Headers Lambda Code
        cd hdrs/ && zip -r ../${PROJECT}-sec-hdrs.zip index.js
        cd ../
        echo Copying Lambda Edge Function Code to S3 Deploy Bucket
        aws s3 cp ${PROJECT}-sec-hdrs.zip s3://${DEPLOYBUCKET}/functions/${PROJECT}-sec-hdrs.zip

    - name: Deploy Static Web CloudFormation Template
      if: "!contains(github.event.head_commit.message, 'dnsprep')"
      run: |
        echo Performing Variable Substitution
        envsubst '${ENV} ${WEBSTACK} ${DNSSTACK} ${REQUESTER} ${PROJECT} ${ORGUNIT} ${FQDN} ${DNSZONEID} ${BUCKETNAME}' < ./aws/static-web.yml > webdeploy.yml
        echo Deploying ${WEBSTACK}
        chmod +x ./cfn_wrapper.sh
        source ./cfn_wrapper.sh
        cfn_wrapper aws cloudformation deploy --template-file webdeploy.yml --stack-name ${WEBSTACK} --force-upload --capabilities CAPABILITY_NAMED_IAM --tags Name=${WEBSTACK} Stackname=${WEBSTACK} env=${ENV} orgunit=${ORGUNIT} project=${PROJECT} role=cloudformation-stack requester=${REQUESTER} reponame=${GITHUB_REPOSITORY}
      shell: bash

    - name: Copy Source Files to S3 Bucket
      if: "!contains(github.event.head_commit.message, 'dnsprep')"
      run: aws s3 cp --recursive src/  s3://${BUCKETNAME}
